name: 'Product of the Day'
type: module
description: 'Adds a block to display the product of the day on the homepage.'
core_version_requirement: ^10 || ^11
package: Custom
dependencies:
  - node:node
