<?php


/**
 * Implements hook_cron().
 */
function product_of_the_day_cron()
{

  $end_date = \Drupal::time()->getRequestTime();
  $start_date = strtotime('-1 week', $end_date);

  $database = \Drupal::database();
  $query = $database->select('product_of_day', 'p')
    ->fields('p', ['nid', 'event_value'])
    ->condition('event_value', $start_date, '>')
    ->condition('event_value', $end_date, '<')
    ->groupBy('nid')
    ->orderBy('nid');

  $results = $query->execute();

  $consolidado = [];
  foreach ($results as $row) {
    $consolidado[$row->nid] = isset($consolidado[$row->nid]) ? $consolidado[$row->nid] + 1 : 1;
  }

  $titles = [];
  foreach ($consolidado as $nid => $count) {
    $node = \Drupal\node\Entity\Node::load($nid);
    if ($node) {
      $titles[$nid] = $node->getTitle();
    }
  }

  $message_body = "List of product<br>";
  foreach ($consolidado as $nid => $count) {
    if (isset($titles[$nid])) {
      $message_body .= "NID: $nid, Title: " . $titles[$nid] . ", Count: $count <br>\n";
    }
  }

  $mailManager = \Drupal::service('plugin.manager.mail');

  $message = [
    'id' => 'drupal_mail_test',
    'headers' => ['Content-type' => 'text/html'],
    'subject' => 'Consolidation of products',
    'to' => 'ja_avila@hotmail.com',
    'body' => $message_body,
  ];
  // Send the email.
  $result = $mailManager->getInstance(['module' => 'simpletest', 'key' => 'drupal_mail_test'])->mail($message);

}

