<?php

/**
 * Implementa hook_cron() para registrar un cron job explícito.
 */
function product_of_the_day_cron()
{
    \Drupal::logger('product_consumer')->notice('El cron job de ProductCronJobSubscriber ha sido ejecutado.');

    $end_date = \Drupal::time()->getRequestTime();
    $start_date = strtotime('-1 week', $end_date);

    $database = \Drupal::database();
    $query = $database->select('product_of_day', 'p')
        ->fields('p', ['nid', 'event_value'])
        ->condition('event_value', $start_date, '>')
        ->condition('event_value', $end_date, '<')
        ->groupBy('nid')
        ->orderBy('nid');

    $results = $query->execute();

    $consolidado = [];
    foreach ($results as $row) {
        $consolidado[$row->nid] = isset($consolidado[$row->nid]) ? $consolidado[$row->nid] + 1 : 1;
    }

    $titles = [];
    foreach ($consolidado as $nid => $count) {
        $node = \Drupal\node\Entity\Node::load($nid);
        if ($node) {
            $titles[$nid] = $node->getTitle();
        }
    }

    $message_body = "Listado de productos y cantidad de consultas en la semana pasada:\n\n";
    foreach ($consolidado as $nid => $count) {
        if (isset($titles[$nid])) {
            $message_body .= "NID: $nid, Título: " . $titles[$nid] . ", Consultas: $count\n";
        }
    }

    $mailManager = \Drupal::service('plugin.manager.mail');
    $module = 'product_of_the_day';
    $key = 'product_consumer_report';
    $to = 'ja_avila@hotmail.com';
    $subject = 'Consolidado de productos consultados';
    $params['message'] = $message_body;
    $params['subject'] = $subject;
    $langcode = \Drupal::languageManager()->getDefaultLanguage()->getId();

    // Enviar el correo.
    $mailManager->mail($module, $key, $to, $langcode, $params);
    \Drupal::logger('product_consumer')->notice($message_body);

}
